### ISSUE TITLE
Grand Design: New SDC 

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/Programme#1]
In progress since March 2023

- [x] 🚀 Pastoral custom platform https://github.com/CodeYourFuture/CYF-Signposts launched April 2023
- [x] 🚀 PD custom platform https://github.com/CodeYourFuture/CYF-PD launched May 2023
- [x] 🚀 Tech custom platform https://github.com/CodeYourFuture/curriculum  launched June 2023
- [x] 🧑‍🤝‍🧑 Learning Together (Flipped) Pedagogy launched July 2023
- [x] 🚀 Coursework Planning System scheduled August 2023
- [ ] 📚 New Curriculum launched July scheduled for first completion December 2023
- [ ] 📈 New tracker in progress...

**Comment by kfklein15** [comment]
This should probably be a milestone/epic with these other as issues of it. Let me know if you want me to do this.

**Comment by SallyMcGrath** [comment]
I'd love for you to do that, @kfklein15 !!! ❤️

**Comment by kfklein15** [comment]
Done. Closing this since I opened #28 and #29
