### ISSUE TITLE
Handover document

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/Programme#101]
- Bring everything to a resolution, that can be resolved
- Handover of things that need to be resolved
     - Tech Ed (except Syllabus)
     - Partnership handover
- List of things we won't do

**Comment by Dedekind561** [comment]
Here is the handover doc: https://docs.google.com/document/d/1bvm9WCfnfWXXz2ShJTk5ATjaQfwq7_Tw3JJhnOYJ6Eg/edit
