### ISSUE TITLE
Slim down documentation from Programme Managers

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/Programme#102]
Review documentations that we created previously and slim them down

**Comment by kfklein15** [comment]
@SallyMcGrath , can you please add the link here?

**Comment by SallyMcGrath** [comment]
https://codeyourfuture.openclass.ai/invite?code=jkGncH1gZ7ZReg

is the thing I think they used most
https://www.youtube.com/watch?v=MBQf-aeuElc&list=PLozA7cloMbPi484EXauIUmITQ4VCgeYPO
https://www.youtube.com/watch?v=4rT46AWYgYA&list=PLozA7cloMbPgeWP7RI9p9HO2-mCFPxiWA
https://www.youtube.com/watch?v=Hbtfil-G0h0&list=PLozA7cloMbPiOvZnMvPGwdQCAeEAroGfR

then we have docs in places like...
https://docs.codeyourfuture.io/
https://docs.google.com/spreadsheets/d/10IizX4sqj04FsfaQMMTIjoxuGkrlEqQqnZvIYCAXjlI/edit?usp=sharing
https://app.gitbook.com/o/-LcSabThbCRVBSHYbXg4/s/-M02BLFbbjegko8GLsDp/
https://docs.google.com/document/d/1vwKuyAslQwWH4DOtfqa20baFili0cupor3LRES6XPgI/edit?usp=sharing
https://drive.google.com/drive/folders/0AL50DhcwkL9rUk9PVA

**Comment by kfklein15** [comment]
@SallyMcGrath 

**[Open AI Fundamentals Tracker](https://www.youtube.com/watch?v=MBQf-aeuElc&list=PLozA7cloMbPi484EXauIUmITQ4VCgeYPO)**: I don't think I have admin access, but could you archive this? We don't have Fundamentals anymore, and we (hopefully) will be tracking it all on the Dashboard. If needed we can create a new video again once we know how to do this.

**[Setting up google class room](https://www.youtube.com/watch?v=MBQf-aeuElc&list=PLozA7cloMbPi484EXauIUmITQ4VCgeYPO)**: I also dont' have admin access to our youtube. This should be archived.

**Github training**
- [Coursework planner](https://www.youtube.com/watch?v=Hbtfil-G0h0&list=PLozA7cloMbPiOvZnMvPGwdQCAeEAroGfR): still ok
- [Adding team to GitHub repo](https://www.youtube.com/watch?v=rAK0gQyV3lY&list=PLozA7cloMbPiOvZnMvPGwdQCAeEAroGfR&index=2): this is ok, but we might have to change how we expect these groups to be set-up, since they are no longer cohort, but batches. Let's discuss on Thursday.
- [Join your GitHub team](https://www.youtube.com/watch?v=9Tpk03qzndc&list=PLozA7cloMbPiOvZnMvPGwdQCAeEAroGfR&index=3): same as above, valid, but might need tweaks
-[ Cohort on GitHub](https://www.youtube.com/watch?v=JUKaiOtjHkE&list=PLozA7cloMbPiOvZnMvPGwdQCAeEAroGfR&index=4): same as above.
- [Mentors, join your team](https://www.youtube.com/watch?v=fZRdEr5SiPY&list=PLozA7cloMbPiOvZnMvPGwdQCAeEAroGfR&index=5): probably still valid, if you are keeping this role.

**CYF Docs**
- I will go through it, but will be a separate ticket since there is a lot that must be updated or changed.
- [Teach Training CYF](https://app.gitbook.com/o/-LcSabThbCRVBSHYbXg4/s/-M02BLFbbjegko8GLsDp/): doesn't work anymore, opens in GitBook rather than the website.

**[Drive](https://drive.google.com/drive/folders/1_rsrFmM762th0VjnljxUBsReuTaIgOkR)**
Will also make a separate ticket for this.

**Comment by SallyMcGrath** [comment]
I've archived those two google classroom videos. I think @Dedekind561 deleted the teacher training site. Nobody ever used it.
