### ISSUE TITLE
Put CMS on curriculum for PD/Emp

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/Programme#104]
- [ ] Get PR from PD syllabus
- [ ] Port to curriculum
- [ ] Test

**Comment by kfklein15** [comment]
https://cyf-guides.netlify.app/admin/

**Comment by kfklein15** [comment]
Thanks, Sally.
@Barny-6 , can you give [this portal a try ](https://cyf-guides.netlify.app/admin/)with one of your Employability pages, please? :) We can update that content without needing PRs.
(I am closing this ticket, but copy the portal link there. If you cannot access it, let me know. I might have to add you to our Netlify account).

**Comment by Barny-6** [comment]
I can access this, will explore publishing something
