### ISSUE TITLE
DLP - DigComp mapping

### ISSUE THREAD

**Issue by AmyCYF** [CodeYourFuture/Programme#11]
- [ ] #12
- [ ] 2. Consolidate the DLP learning objectives written by Amy (23 November)
- [ ] 3. revised by Amy (30 November)
- [ ] 4. Identify Gaps in the program (7 December)
- [ ] 5. Fill gaps in the program (21st December)
- [ ] 6. create a short skills test (with exclusions) - needs to also be available offline (18th January)

Learning Objectives and the Dig comp on a spreadsheet:
https://docs.google.com/spreadsheets/d/14ZheXzYd_AK39x0LnKVual_bq8BJ3eK-Fdw-0PgHbVM/edit?usp=drivesdk

Digcomp test (existing)
https://digital-skills-jobs.europa.eu/digitalskills/screen/questionnaire/generic

Dig comp framework: 
https://joint-research-centre.ec.europa.eu/digcomp/digcomp-framework_en#:~:text=The%20DigComp%20framework%20identifies%20the,the%20source%20and%20its%20content.

By Jan 2024

**Comment by kfklein15** [comment]
FigJam mapping by Sally: https://www.figma.com/file/Izj3VJVjr2PkFUNITIt0Jn/DLP-Mapping?fuid=1129722015347451758&source=email_invite

**Comment by SallyMcGrath** [comment]
Let's do this in our offsite.

**Comment by SallyMcGrath** [comment]
@AmyCYF we did do this in the offsite BTW! I told you in person but I don't think maybe I communicated it clearly enough
