### ISSUE TITLE
Portfolios Module

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/Programme#13]

**Comment by SallyMcGrath** [comment]
https://curriculum.codeyourfuture.io/portfolio/

I'd like to talk about this this week if possible and get a rough cut out.

**Comment by kfklein15** [comment]
What I am planning to do today, so input would be great is outlined below.

3 Sprints
- Sprint 1 is the intro sprint: it includes Portfolio Module goals, SMART goals and the start of project work
- Sprint 2 has a list of employability things we would like to be discussed + stand-up of the team + planning/refinement + pairing
- Sprint 3 has a placeholder for a guest-speaker + employability things (same list as sprint 2) + demo + retrospective. pairing

The idea with this is to give a guide but not close it too much and not have to create 8 sprints with different employability/product content.

What are your thoughts, @SallyMcGrath?
If you are ok with it I can raise the PR and send it this morning.

**Comment by kfklein15** [comment]
This has been done.
