### ISSUE TITLE
What are the measure to know how healthy is a community? - Rubric

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/Programme#14]

**Comment by SallyMcGrath** [comment]
There are some interesting Slack analytics we can think about. For community channels, number of members vs number of posters. For example 

 channel |  members | participating | % rate
---|---|---|---
nw6 | 38 | 25 | 69%
wm5 | 66 | 25 | 38%
gla6| 124| 36 | 29%
lon10 | 197|36 | 18%
lon9 |196 | 43 | 21%

**Comment by MarianaVazquezCYF** [comment]
oh woow thanks! I was not thinking of online communities (slack) I was thinking of the in-person classes! This is the document I created, I will add a part for behaviour on Slack! 

https://docs.google.com/document/d/1MocNTxyXOMAAeZWnfcImJiaGAKiu1RgnNVvQaXEFDM0/edit#heading=h.syjvq65w9jdx

**Comment by MarianaVazquezCYF** [comment]
This is the rubric! we need to finish reviewing it!https://docs.google.com/spreadsheets/d/1ycUYjkc1E68yS0tILouPL5Nf_KTxEBLgAoqiV_jvi50/edit#gid=558327456 and volunteers will tell us their strategy

**Comment by SallyMcGrath** [comment]
> This is the rubric! we need to finish reviewing it!https://docs.google.com/spreadsheets/d/1ycUYjkc1E68yS0tILouPL5Nf_KTxEBLgAoqiV_jvi50/edit#gid=558327456 and volunteers will tell us their strategy

I've made a ZILLION comments. 😓

**Comment by Dedekind561** [comment]
Think the strategies points on the checklist should be separated out into different issues.
