### ISSUE TITLE
Community aspects that should happen every saturday! (Example, volunteers meeting every saturday, lunch together, having at least 2-3 volunteers)

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/Programme#15]

**Comment by SallyMcGrath** [comment]
Connecting this to helping the Proms focus on the strategy not the course delivery, it would be really useful to do a mini active learning exercise with them on some hows, like:

- **how** do I get 3 volunteers to show up every week (by spending my time recruiting and onboarding volunteers and connecting volunteers to each other so they form a team, not by posting in Slack THERE'S NO ONE SIGNED UP and then going to class myself)

- **how** do I make lunch happen? (there may be multiple strategies, and I might have to intervene a few times over the course to keep it going)

- **how** do I encourage volunteers to use Saturdays to improve course delivery? (I set the expectation in onboarding that there are volunteer activities to do on Saturdays: code review, standup, retro, tracker review; I ask Tech Ed to do training on class days;  I invite people out for coffee/drinks after class from time to time...)

**Comment by MarianaVazquezCYF** [comment]
yes!! we can write a strategy for all of this! This is in my backlog as I want to work on this in Portugal !
