### ISSUE TITLE
onboarding for cohort founders

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/Programme#17]

**Comment by SallyMcGrath** [comment]
Hey - I would be really interested in knowing how onboarding works for volunteers these days. Do you have links you can share with me?

**Comment by MarianaVazquezCYF** [comment]
Yes, this is the main document for all volunteers including cohort founders! However, cohort founders should have a deeper onboarding! https://docs.google.com/document/d/11YoZbTasrQb6lCcDQUSBbpIFr2ruKhGWiefiBDIL9wM/edit

**Comment by kfklein15** [comment]
Some points from me for the cohort founders:

- **Organise, but not deliver:** A strong training explaining this so they do not get overloaded
- **Hire volunteers**: having a good and reliable team is key
- **Flipped classroom**: they must be the advocate for this
- **Lead by example**: stay back and let others do things, but give feedback when needed (to volunteers and trainees)
- **Clarity on reaching out** when needing help: what should go to volunteers, what should go to staff
