### ISSUE TITLE
Strategy to make volunteers self organise

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/Programme#18]

**Comment by SallyMcGrath** [comment]
I have some thoughts here on doing a set of mini trainings with the Proms - would love your input/help.  Here are my notes 

https://docs.google.com/document/d/1lyZdgaUJwSxWaquyRAbJo3Hl0pSQY8S6tm71UZlvTGg/edit?usp=sharing

the idea would be to pose a topic and spend 2 minutes on a Jamboard identifying problems and then 5 minutes identifying solutions, then 3 minutes picking one thing to do right now and sharing that with each other. The topics are listed on the sidebar. 

We all think that self-organisation is being suppressed by our behaviour as staff, so part of it is going to be retraining ourselves to really empower and enable our amazing, highly skilled, dedicated volunteers.

**Comment by Dedekind561** [comment]
I've been thinking a fair amount about what to focus on and then came across this issue - I think we should convert it into a milestone and break this issue up

**Comment by MarianaVazquezCYF** [comment]
I agree, I will close this ticket! and I think this is also part of the rubrics and the strategy where volunteers themselves tell us their plan after doing a self assessment !
