### ISSUE TITLE
Onboarding volunteers

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/Programme#19]

**Comment by SallyMcGrath** [comment]
#17 or here - do you know where this lives?

**Comment by kfklein15** [comment]
What is this ticket about? Can we have a description on top (just edit it) so we know what it is about, please?

**Comment by SallyMcGrath** [comment]
Common questions. I have built a few - using custom and things like Poe. So far the answers are not reliable enough to use. (But I think just time will solve this as the tech gets better).

**Comment by MarianaVazquezCYF** [comment]
I will close this ticket because we have "solved" this with slack canvas and Karen and I are mapping a new process using bots!

**Comment by kfklein15** [comment]
@MarianaVazquezCYF , should I raise the epic and stories for the rest of this work on the Community board or on the Programme board?

**Comment by MarianaVazquezCYF** [comment]
Ideally I would like to have it in both ! but the one I use the most is the community board!
