### ISSUE TITLE
New Curriculum SDC

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/Programme#2]
This is being run on 

https://github.com/CodeYourFuture/curriculum/  
https://github.com/orgs/CodeYourFuture/projects/105

By @CodeYourFuture/global-syllabus / #cyf-syllabus-tech

Milestones are on that project. Final deadline added here.

**Comment by kfklein15** [comment]
Curriciulum also includes PD. @CodeYourFuture/pd-syllabus-team is also doing it. Let me know if you prefer me to create a different ticket for it.

**Comment by SallyMcGrath** [comment]
No add it here --makes sense!
