### ISSUE TITLE
Rhythm of the week

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/Programme#21]
Instead of building ever more complex curricula, we want a simpler format that structures productivity. We want a rhythm of work that is separate from the subject and location of that work. We can build a canvas to show this pattern.

https://docs.google.com/document/d/1h5YAI4zQVislSKRb2Sx1_mYztsMXg3xIZ5lYRBUVSmI/edit?usp=sharing

**Comment by MarianaVazquezCYF** [comment]
@kfklein15 this is an example of how I thought that this project: rhythm of the week was going to be delivered on this way, but then it changed after our meeting! 

Update ticket: I will close this, and change it for a milestone!
