### ISSUE TITLE
Define when trainees graduate

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/Programme#25]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SallyMcGrath** [comment]
@lilianabermudes can you update this ticket as it looks like a blank template. 🙏

**Comment by lilianabermudes** [comment]
Thanks, Sally. This has been defined, so I'll close this ticket. Graduation = employment. 

(But there's another Ops open ticket regarding the end date of a cohort, which is needed for Capgemini and other reports).
