### ISSUE TITLE
New Trainee Tracker

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/Programme#29]
**Is your feature request related to a problem? Please describe.**
Current trainee tracker does its job, but we want to have software in place instead of a spreadsheet

**Describe the solution you'd like**
@SallyMcGrath to detail 

**Describe alternatives you've considered**
@SallyMcGrath to detail

**Additional context**
-

**Comment by SallyMcGrath** [comment]
I think this is on another board and in another project now
