### ISSUE TITLE
PD Milestone: test setup and iteration 1

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/Programme#31]
**Background**
On #26 we identified an opportunity to test if we could use Milestones on GitHub Projects to identify the levels of PD work as well as min/max number of coursework.
Some background information about how milestones work at CYF:
- [Milestones Descriptions](https://docs.codeyourfuture.io/leaders/running-the-course/assessment/milestones)

 
**Acceptance criteria**
1. Create my coursework board
2 Batch clone 1 module (use [Kamino](https://chromewebstore.google.com/detail/kamino/ffdebockfdjileaojbbccofhgncmioaf)) OR per competency 
3. Define milestones 
       1. Key and Mandatory coursework only
       2. 3 levels: Level 1, Level 2, Level 3 - to be defined with [SIFA](https://sfia-online.org/en/about-sfia/how-sfia-works)
       3. Dealbreaker: is "Key" the dealbreaker? 
4. Define min/max count of coursework per Level and per timeframe
5. Make notes of any constraints/issues in the process

**Owner**: Lara and Karen
**Stakeholder:** 1 volunteer from PD Syllabus and 1 from Coursereview
**Approver**: Sally

**Technical notes**
[GitHub Milestone API](https://api.github.com/repos/CodeYourFuture/curriculum/milestones)
Must have info in bold
```
id integer or string yes The ID or URL-encoded path of the project owned by the authenticated user
**title string yes The title of a milestone**
description string no The description of the milestone
**due_date string no The due date of the milestone (YYYY-MM-DD)**
start_date string no The start date of the milestone (YYYY-MM-DD)
```

**Comment by kfklein15** [comment]
The coursework planner has been cloned. We need to think about the levels, @LaraHuzjan

**Comment by kfklein15** [comment]
Lara and I created the first version for Communication/English Language.
We need to validate it with Sally.

**Comment by kfklein15** [comment]
This was reviewed with @SallyMcGrath today and is a good starting point and seems to be going in the right direction. I will raise the tickets discussed in the meeting and link them back to this one as well as add it to the same milestone.

**Comment by SallyMcGrath** [comment]
👋 I'm looking for the resources -- the boards, repos, issue, spreadsheets etc related to this project. Is there an obvious place I should be looking?

**Comment by kfklein15** [comment]
We are still finalising this work (ticket 47 was the last one). I will add details to your ticket if Lara and I are comfortable with it after our meeting tomorrow.
Thanks for raising this.
