### ISSUE TITLE
Quality: Feedback for our Programme

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/Programme#32]
**Background**
On our [Quality Improvement plan](https://docs.google.com/document/d/1oybQr54zKixDRkAKcgeUs2br6rkKQuovmUxCjnMBjf8/edit#heading=h.mtmcgo8yxfeb) we have an action of revising the curriculum feedback

**Acceptance criteria**

- Define the process for feedback of our Programme
- Publish it

Owner: @kfklein15 
Stakeholders: @Dedekind561 @LaraHuzjan @SallyMcGrath 
Approver: @SallyMcGrath

**Comment by kfklein15** [comment]
PD Syllabus team has suggested [this form](https://github.com/rogerspooner/tusb_hid/issues/new?assignees=&labels=PD&projects=&template=feedback-on-pd-syllabus.yml&title=Feedback+on+XXX) to get PD feedback

Since ideally we want a solution for the overall curriculum, my open questions are:
1. Can we use similar/same for Tech Ed? If yes, who needs to be involved?
2. Should the forms be kept in each Syllabus repository (PD and Tech Curriculum)?
3. Identify other places this should be communicated (i.e. Canvas for the Tech and PD Syllabus teams, Canvas of each cohort, etc.)?

@SallyMcGrath @Dedekind561 and @LaraHuzjan , would love your input on this. 
Thanks!

**Comment by SallyMcGrath** [comment]
1. The PD form is not suitable for the Tech Ed curriculum. We already use FOSS standard processes for revision and it would not be an improvement to use something non-standard. We want to teach our trainees to participate in improvements in the way a developer should.


BTW, I sent you an email and document regarding this meeting (when I woke up as it was at 6am 😉 ) . It's here https://docs.google.com/document/d/1EaqTpgv80QCo5ySUnkdp9wnqj3x7IcTxSfQeWaFDsuA/edit?usp=sharing

**Comment by kfklein15** [comment]
Thanks, @SallyMcGrath . I did this on the train to Manchester, and the internet didn't let me open the files to read everything :) Thanks for updating this here. I'll take a look at it asap.

To ensure we are all on the same page, can you link or explain your FOSS standard process?
Do you see why we should NOT use the same Tech Ed process for PD?

**Comment by SallyMcGrath** [comment]
1. To ensure we are all on the same page, can you link or explain your FOSS standard process?

Sure - it's just the same thing we expect from volunteers - to open an issue explaining the problem or (ideally) a PR with the fix. We guide trainees to provide their feedback directly to the codebase in this way. It takes a bit more work but it's a really valuable developer skill and we always try to make our processes be useful on their own terms, not just be useful to CYF/admin. So we frame it as bug reporting, based on the basic one that comes with GitHub, and iterate as needed. 

Here you can see some examples. Here's an issue created by a trainee explaining their fix to a piece of coursework

https://github.com/CodeYourFuture/curriculum/issues/510

Here's a PR a trainee opened in class with a mentor fixing a mistake

https://github.com/CodeYourFuture/curriculum/pull/380

Here's a PR contributed by an outside contributor addressing an improvement requested by a volunteer

https://github.com/CodeYourFuture/curriculum/pull/491

2. Do you see why we should NOT use the same Tech Ed process for PD?

I don't think it's massively different, but I wouldn't want to place a bunch of obstacles in front of the PD team by requiring they all learn pullreqs and code review. I feel like there's been a lot more development happening in PD now you're in your own CMS and not trying to set up local repositories etc. It's not worth the candle. For Tech Ed I think it is worth it, as we want everyone to think of the programme as software we are all using to produce developers, and engage with it as software they can iterate and improve themselves.

**Comment by kfklein15** [comment]
Thanks for the explanation, @SallyMcGrath . Makes sense to me.
@LaraHuzjan , I believe if everyone on the PD Syllabus is happy with the PD feedback form format, we can open another ticket to discuss the pilot/communication of it, etc.

Sally, I have reviewed your doc, leaving comments on it directly.

**Comment by kfklein15** [comment]
We have added all our[ notes to our document](https://docs.google.com/document/d/1Xi6q9_YAykWD-_nMffzafn5b_SZMLyawuietwxz1ZwU/edit).

I have created the [tasks for PD Duolingo. ](https://github.com/CodeYourFuture/CYF-Staff-Tickets/milestone/17)

@SallyMcGrath and @ClaireBickley , if you could create the next tasks for you too would be great.

**Comment by LaraHuzjan** [comment]
@kfklein15 ticket has been added. 
Thanks for the feedback!
