### ISSUE TITLE
New Entry and Exit criteria to be published to WM5 and NW6

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/Programme#34]
**Background**
We have worked on the new Launch project and created new entry and exit criteria. I started a [thread on Slack](https://codeyourfuture.slack.com/archives/C05KCLBLG48/p1704461364182599) and realised it's best to have a ticket. 

**Describe the solution you'd like**
- New [Exit](https://docs.google.com/document/d/1eS6sYRP8Jw-siL_cqA-ql_13XWbWhMJlTx9d0H4b47A/edit#heading=h.8bipiccmzk3c) and [Entry](https://docs.google.com/document/d/18e84jL43b_xxLQCKROzIePDwq-gvxKcgZl7LTorPF3I/edit#heading=h.8bipiccmzk3c) Criteria for Launch to be approved by @SallyMcGrath ✅ and @Dedekind561 
- Communicate to cohorts WM5 and NW6
- Update the curriculum links
- Set old criteria as [OLD] on drive and move to Archive

**Comment by SallyMcGrath** [comment]
FYI this doc is in the Bin

https://docs.google.com/document/d/18e84jL43b_xxLQCKROzIePDwq-gvxKcgZl7LTorPF3I/edit#heading=h.8bipiccmzk3c

**Comment by kfklein15** [comment]
I removed it from the bin. Thanks for letting me know.

**Comment by SallyMcGrath** [comment]
Looks great Karen. Thanks for all your work on this.

**Comment by kfklein15** [comment]
Asked on the Launch planning Slack: https://codeyourfuture.slack.com/archives/CCTV4D93K/p1707216531483259

**Comment by SallyMcGrath** [comment]
@Dedekind561 please take a look when you can

**Comment by kfklein15** [comment]
We will integrate10 minute reminder blocks into the day plans at:

- the start of React ( React sprint 1 )
- the start of Databases  ( Databases sprint 1 )
- Or other places where you think it would be useful to remind the cohort about the Launch (edited) 

Captured here: https://github.com/CodeYourFuture/Programme/issues/57

**Comment by kfklein15** [comment]
- current criteria was set as [old](https://docs.google.com/document/d/1jMxqI0L7IKFENCQ8Lw-D1lhnj3c3RZI_WK808wG4YJM/edit?tab=t.0#heading=h.8bipiccmzk3c) on google doc
- new criteria docs set as live on google doc
- update the links on the PD CMS for the launch prep
- Posted on NW6 general and WM announcements

Must update the form - [ticket](https://github.com/CodeYourFuture/launch_module_planning/issues/9)
