### ISSUE TITLE
Orientation of new volunteers is done by community on Saturdays

### ISSUE THREAD

**Issue by Dedekind561** [CodeYourFuture/Programme#35]
## User story

As a TRAINEE OR VOLUNTEER,
Whilst participating in A SATURDAY CLASS,
I know how to WELCOME AND ORIENT A NEW VOLUNTEER TO THE COMMUNITY,
So that new volunteers have a minimal amount of context to get started as a teaching assistant on Saturdays

**Comment by Dedekind561** [comment]
## Acceptance criteria

- [] Day plan contains instructions for morning orientation
- [] Morning orientation welcomes new volunteers
- [] Morning orientation describes the plan for the first half of the day and how it is organised
- [] Morning orientation will nominate a timekeeper

**Comment by MarianaVazquezCYF** [comment]
This is also related to what you were saying @haldenb
