### ISSUE TITLE
Volunteers and trainees stick to timings on Saturdays

### ISSUE THREAD

**Issue by Dedekind561** [CodeYourFuture/Programme#36]
## Problem
TIme is often wasted during Saturday classes. Whilst we'll never have a situation where everyone sticks to timings exactly, we must strive towards it to improve our time management as a community. Otherwise we end up with a time blancmange.

## User story

As a trainee or volunteer,
While participating in a Saturday class, 
I know how to keep time for a morning or afternoon session,
So that we use time efficiently and effectively throughout the day

**Comment by SallyMcGrath** [comment]
Can you link the progress so far on this, @Dedekind561 

Like maybe the morning orientation blocks and anything else?

**Comment by Dedekind561** [comment]
Morning orientation blocks have been merged - I will set a date for the milestone in Google Calendar so we can check that this piece of work has been reviewed with WM5 / NW6 later on in the course.
