### ISSUE TITLE
Volunteers and trainees understand and maintain the rhythm of the week

### ISSUE THREAD

**Issue by Dedekind561** [CodeYourFuture/Programme#37]
## Context

https://docs.google.com/document/d/1h5YAI4zQVislSKRb2Sx1_mYztsMXg3xIZ5lYRBUVSmI/edit

## User stories

As a TRAINEE OR VOLUNTEER,
I know WHAT THE RHYTHM OF THE WEEK is,
So that WE BROADLY UNDERSTAND WHAT TO DO AND WHEN during a typical week at CYF

(Already being implemented in https://github.com/CodeYourFuture/Programme/issues/21)

As a TRAINEE OR VOLUNTEER,
I know how to reinforce THE RHYTHM OF THE WEEK,
So that we don't lose momentum when the class is running.

**Comment by kfklein15** [comment]
Removing this from the board since it will have to broken down further
