### ISSUE TITLE
Trainee Onboarding Journey

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/Programme#4]
### Problem:

The trainee onboarding journey is a bit chaotic and the messaging is confusing. We do lots of admin and manually move people through the system and people can get lost. 

### Actions taken:

I have researched the journey, mapped the current situation from the trainee's perspective, and then reorganised it to simplify a bit. I've put that out for consultation with Proms and will leave it out for a week.

https://miro.com/app/board/o9J_kujEdws=/?moveToWidget=3458764561300661427&cot=14

### Next steps:

1. Identify as many simplifications as possible and make them.
2. Write the boilerplate messaging for each contact stage and remove all the ad hoc stuff
3. Identify the biggest bottlenecks that cannot easily be removed and turn them into projects

### Subtickets

- [x] #6 
- [x] #7 
- [x] Prom/vol training

**Comment by kfklein15** [comment]
Adding here some of the actions

**Ongoing**
1. Fixing the applicant page on Dashboard - [Epic/Milestone](https://github.com/CodeYourFuture/tech-team/milestone/44) for the Trainee onboarding steps (Agreement, Slack agreement, PC Form, etc.)


**Future (do we agree on these?)**
1. Review the Steps on ITD - do need versions or should we just have an "archive" options and keep dates
2. Review PD Steps - replace Motivation Letter
3. Replace CEFR with English test ([Duolingo practice](https://englishtest.duolingo.com/test/practice)) (PS: We can then have a proper certificate test in end of Fundamentals, which would mean people would not be allowed into SDC)

**Comment by SallyMcGrath** [comment]
The Duolingo certification is such a blessing!

**Comment by SallyMcGrath** [comment]
I think this is done and the rest fold into Sheffied
