### ISSUE TITLE
Volunteer rhythm of the week Thursday Code Review

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/Programme#50]
So far, we have a volunteer who would like to coordinate Thursdays of code review! She doesn’t have any tech experience and in my opinion, this shouldn’t be a problem as she will only coordinate and promote the session! However, what are the things that she should know about volunteers doing code reviews?

My plan:

- ask an experienced volunteer who always does code reviews to share with her a video tutorial about how they do code review. This will be just for her reference to know what to expect from the session

Stakeholders and approvers ; @Dedekind561 @SallyMcGrath @kfklein15

**Comment by kfklein15** [comment]
Get the volunteer interested in doing Code Review to talk to Altom to start working on Code Review to unblock Altom.
Once this is piloted, the volunteer should do the same work with WM5 cohort founders.

**Comment by MarianaVazquezCYF** [comment]
I made the tutorial for Janhavi, now I am waiting for a response about when she is available to start the code reviews thursday

**Comment by MarianaVazquezCYF** [comment]
Janhavi shared with me,  that she will start this task this thursday

**Comment by kfklein15** [comment]
@MarianaVazquezCYF 
1. Create a Code review invite for Thursday, which anyone can start
2. Ask the new volunteers who want to help with Code review to join/lead this. 
3. Ask the volunteers to create a workflow on Slack of this repeat calendar invite on the code review channel

**Comment by MarianaVazquezCYF** [comment]
@haldenb is taking this, because he already. has a strategy that is working and he is managing volunteers
