### ISSUE TITLE
Volunteer rhythm of the week: On fridays we do demos!

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/Programme#51]
Laura, one of our WM trainees will organise on Friday we do demos! For this, she will invite all the community to share their demos in a call on fridays! 

For this ticket I need to do:

- [ ] Make a video tutorial about how to promote and invite people to their communities
- [ ] Make a document with a checklist to guide people with the channels where they should invite people 
- [ ] Ask Laura to make a sign up sheet where people interested shows their demos 
- [ ] Agree with Laura in a date to start this idea!

**Comment by MarianaVazquezCYF** [comment]
I am still trying to book a meeting with laura!

**Comment by kfklein15** [comment]
@MarianaVazquezCYF 
1. Create a demo on Friday invite, which anyone can start
2. Ask the new volunteers who want to help to go to the demos AND help with communication
3. Ask the volunteers to create a workflow on Slack of this repeat calendar invite on the general channel
4. Ask volunteers to create a canvas and reference to times, channels invites

**Comment by MarianaVazquezCYF** [comment]
The event has been created! 

New challenge:

-0 engagement to show their demos! I will need to work on the following:

- [ ] ask tech leader to share demos
- [ ] Persuade people to show their demos, mentioning that is the opportunity to share their work in front of tech leaders
- [ ] find a wider audience! So far we have 4 people coming to the online event in 2 weeks https://www.meetup.com/techforall-london-code-your-future/events/300656535/
