### ISSUE TITLE
Day plans remind a cohort about the upcoming Launch module

### ISSUE THREAD

**Issue by Dedekind561** [CodeYourFuture/Programme#57]
We want to train the community to reference and act upon the day plan when they're together on Saturday.
As part of this goal, we want to use the day plans to remind trainees about the upcoming Launch module.

## Acceptance criteria

- [ ] A Launch reminder block is integrated into the React sprint 1 day plan
- [ ] A Launch reminder block is integrated into the Databases sprint 1 day plan
- [ ] The Launch reminder block points to [Entry criteria](https://docs.google.com/document/d/18e84jL43b_xxLQCKROzIePDwq-gvxKcgZl7LTorPF3I/edit)

## Stakeholder
@SallyMcGrath 

## Approver 
@kfklein15

**Comment by SallyMcGrath** [comment]
I think this goes on curriculum

**Comment by kfklein15** [comment]
@Dedekind561 , I just found this on a sprint of March. Do we need to bring this to this sprint?

**Comment by SallyMcGrath** [comment]
obsolete
