### ISSUE TITLE
TOJ: Boilerplate Messaging

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/Programme#6]
- [x] ITD Steps
- [x] ITD Fail --> Return
- [x] ITD Pass --> to Rainbird
- [x] Rainbird Reject  --> Return
- [x] Rainbird Accept --> to Class Prep
- [x] Class Prep Steps : Signposts
- [x] Fundamentals Reject  --> Return
- [x] Fundamentals Accept --> to SDC
- [x] SDC Prep: Signposts

**Comment by kfklein15** [comment]
This will use the "Class Preparation" on Dashboard.
