### ISSUE TITLE
Setup boards for discussions about current problems

### ISSUE THREAD

**Issue by Dedekind561** [CodeYourFuture/Programme#67]
Need more info to focus the work for upcoming Sheffield milestones

Break down some key problems into areas for discussion with folks in the relevant domains and then move on from there. There may be some questions that we already know the answer to 

## Definition of done 
- [x] Have set up boards for discussions across different areas for Sheffield launch
- [ ] Identify areas of agreement/disagreement across CYF staff

**Comment by SallyMcGrath** [comment]
Can you put links on this ticket please @Dedekind561 ?

**Comment by Dedekind561** [comment]
Yes. Here are the boards: [https://github.com/CodeYourFuture/Programme/discussions/68](Cohort founder - roles and recruitment) and [https://github.com/CodeYourFuture/Programme/discussions/69](Outreach and new cohort advertising)

**Comment by kfklein15** [comment]
The second point is a bit too large, so we'll take this discussion separately before raising more discussion boards.
