### ISSUE TITLE
TOJ: Bottleneck Projects

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/Programme#7]
- [ ] Class Preparation Course on Dashboard
- [x] Laptop Loan Process
- [x] Expenses
- [ ] Trainee Email
- [x] Personal Circumstances
- [ ] Eligibility and Suitability Comms

**Comment by kfklein15** [comment]
Should we change this ticket to an Epic/Milestone and have them as individual issues? Some of them are ongoing already, or have dependencies?
