### ISSUE TITLE
Sign off new strategy (28.02) Sheffield

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/Programme#71]
This is the link to the strategy: https://docs.google.com/document/d/1Pfzt1S2gQ7YHRXnyjB1FaxIFLSPaOeEZfXixwlFlm3I/edit
On this ticket I was previously summarising the strategy with Germans comments. Now the strategy is ready but need the sign off of the programme team!

**Comment by SallyMcGrath** [comment]
We need to work with Amy - I agree it's a good idea and we could get moving on it quickly as she's super organised

**Comment by MarianaVazquezCYF** [comment]
Ok perfect. I will add this to the timeline then!

**Comment by MarianaVazquezCYF** [comment]
Its done with the new strategy and new timeline! according to the strategy, next inmediate steps for this quarter should be:

- [ ] Sign off the strategy 
- [ ] Talking with Amy about her participation !

**Comment by SallyMcGrath** [comment]
Great! Let's assign to @gbencci so he can see if we've met the criteria or if there are more things we need to do.

**Comment by kfklein15** [comment]
@gbencci , we need your official sign-off of this strategy. Can you let us know if you are happy with it, please? We would like to ideally finish this in this sprint (finishes on 19th March), so if changes are needed let us know asap.

**Comment by gbencci** [comment]
Hi All! The steps are all right. We just need to assign responsibilities and define success in the different areas. A first essential step is to meet with the volunteers and communicate what is expected from them, so I left some suggested notes to refine this by the time we talk to them. They need to know what we are alll aiming for.

Overall, the sequence is quite logical, so my comments are only about making it clearer for us and the community who is doing it and what we are achieving

**Comment by MarianaVazquezCYF** [comment]
Hey team I have seen that the delivery team is working on this for the DL! so I will close this ticket

**Comment by SallyMcGrath** [comment]
Hm, no they aren't signing off any strategy. The delivery team doesn't set strategy.
