### ISSUE TITLE
Build replacement for Rainbird to unblock new classes

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/Programme#72]
**Is your feature request related to a problem? Please describe.**

Rainbird isn't usable and it doesn't look like it will be any time soon. This means we can't launch classes. 

I tried to use it for CYF+ and it's completely unusable, with users not being logged in the DB, blank pages, all kinds of errors.

**Describe the solution you'd like**

We need something to crunch the eligibility and suitability numbers in order to launch a class (any class) without manual admin

I'd love a fixed Rainbird
If I can get a usable/hobbled Rainbird eg the embedded version I would take that
Otherwise I will write something, likely a google form

**Describe alternatives you've considered**

I've tried to get Rainbird fixed but it's just not happening, or not in time

**Additional context**

- Write the criteria as propositional logic
- Compute
- Hack up an interface

**Comment by SallyMcGrath** [comment]
https://form.jotform.com/240594751513053

**Comment by kfklein15** [comment]
It needs to finish testing and writing testing.

**Comment by SallyMcGrath** [comment]
Done. I won't link the sheet on here as it;s a security risk
