### ISSUE TITLE
Review Trainees & Grads Survey Planning 

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/Programme#8]
https://drive.google.com/drive/folders/1yn0YAyJqZscWeQ2C-OPjGURxVDjerRj7

--> Do we need them? How frequently?
--> What questions do we need to ask that are useful for you in improving the Programme and Products?

**Comment by kfklein15** [comment]
Was this only for WMCA?

**Comment by kfklein15** [comment]
@lilianabermudes , do we still need this? Otherwise, I will close it

**Comment by lilianabermudes** [comment]
We do, but this is the discussion we're having with @ClaireBickley :-) So I'll close this one, and we open a new ticket
