### ISSUE TITLE
Create createria for attendees from more regions to present their demos at the job fair

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/Programme#82]
I want to meet with Karen to understand what criteria we will use to select the demos that can be presented during the job fair in London! We have space for 4 or 5 more projects from other regions. 

what is clear to me so far is the following:

- At least one member of the team, should be unemployed or not having a job in tech as developer
- All the members should be trainees or graduates 
- All the demos should be made in teams? so no solo presentations???

**Comment by kfklein15** [comment]
Duplicated with https://github.com/CodeYourFuture/CYF-Staff-Tickets/issues/670
