### ISSUE TITLE
Personal Circumstances: Map, Rationalise, and Destroy

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/Programme#9]
# related to
- [x] #10 
- [ ] #4 

# steps
- [x] Collect all s.data
- [ ] Map to new format
- [x] Close down forms and inputs
- [ ] Archive collation
- [ ] Destroy duplicates

**Comment by ClaireBickley** [comment]
I've sourced and backed up everything I've been able to find. What is needed for the next steps?

**Comment by SallyMcGrath** [comment]
Now it's mapping

**Comment by kfklein15** [comment]
Isn't this done? Or at least ongoing?

**Comment by SallyMcGrath** [comment]
The mapping has to be done, manually -- all 1000 entries need to be assigned to the new system

**Comment by SallyMcGrath** [comment]
@ClaireBickley should this ticket be handed over to you?

**Comment by ClaireBickley** [comment]
I can take this, but will need a bit of an explainer on the steps.

**Comment by SallyMcGrath** [comment]
Book a call, @ClaireBickley ?
